/** Shared alert rule type → Chinese label mapping (default fallback) */
export const RULE_TYPE_CN: Record<string, string> = {
  spc_violation: 'SPC失控',
  out_of_spec: '超规格限',
  trend_detected: '趋势异常',
  mean_shift: '均值偏移',
  high_variation: '变异过大',
  low_cpk: '能力不足',
  cpk_below_target: 'CPK预警',
  cpk_low: 'CPK预警',
  spec_limit_breach: '规格越限',
  above_usl: '规格越限',
  below_lsl: '规格越限',
  nelson_1: 'Nelson规则1',
  nelson_2: 'Nelson规则2',
  nelson_3: 'Nelson规则3',
  nelson_4: 'Nelson规则4',
  nelson_5: 'Nelson规则5',
  nelson_6: 'Nelson规则6',
  nelson_7: 'Nelson规则7',
  nelson_8: 'Nelson规则8',
  prediction_above_usl: '预测超上限',
  prediction_below_lsl: '预测超下限',
}
